const test = require("node:test");
const assert = require("node:assert/strict");
const {
  buildLoginToken,
  desDecode,
  desEncode,
  dhExchange,
  dhSecret,
  encryptLoginToken,
  framePackage,
  hmac64,
  parseAuthResponse,
} = require("../protocol/cadGatewayCrypto");

function hex(value) {
  return Buffer.from(value).toString("hex");
}

test("gateway crypto matches vectors generated by the Unity C# Crypt2 implementation", () => {
  const clientKey = Buffer.from("0102030405060708", "hex");
  const serverKey = Buffer.from("090a0b0c0d0e0f10", "hex");
  const challenge = Buffer.from("1112131415161718", "hex");
  const clientExchange = dhExchange(clientKey);
  const serverExchange = dhExchange(serverKey);
  const secret = dhSecret(serverExchange, clientKey);
  const tokenOptions = {
    userId: "12345",
    channelToken: "token-value",
    platform: "3",
    channel: "CH",
    serverNode: "game1",
  };

  assert.equal(hex(clientExchange), "984e1418283235ed");
  assert.equal(hex(serverExchange), "f5fc02c8e2cfbd3c");
  assert.equal(hex(secret), "78ab0d3f882c1787");
  assert.equal(hex(hmac64(challenge, secret)), "2cabe7d110398cd3");
  assert.equal(buildLoginToken(tokenOptions), "12345:token-value:3:CH::game1:1:");
  assert.equal(
    hex(encryptLoginToken(secret, tokenOptions)),
    "fd52a891b59a8e5e51ee06a6d5414fb02f48863a5405d5469b308b2eec07c8f6ceb690b8449ce517",
  );
  assert.equal(
    desEncode(secret, Buffer.from(buildLoginToken(tokenOptions))).toString("base64"),
    "/VKokbWajl5R7gam1UFPsC9IhjpUBdVGmzCLLuwHyPbOtpC4RJzlFw==",
  );
  assert.equal(
    desDecode(secret, encryptLoginToken(secret, tokenOptions)).toString("utf8"),
    buildLoginToken(tokenOptions),
  );
});

test("parseAuthResponse decodes the gateway redirect fields", () => {
  const fields = [
    "account-1",
    "7",
    "game-host",
    "10001",
    "127.0.0.1",
    "game1",
    "42",
    "session-value",
  ];
  const payload = Buffer.from(
    fields.map((field) => Buffer.from(field).toString("base64")).join("@"),
  ).toString("base64");
  const result = parseAuthResponse(`200 ${payload}\n`);

  assert.equal(result.accountId, "account-1");
  assert.equal(result.subId, 7);
  assert.equal(result.serverIp, "127.0.0.1");
  assert.equal(result.serverName, "game1");
  assert.equal(result.uid, 42);
  assert.equal(result.sessionKey, "session-value");
});

test("framePackage writes the same two-byte big-endian length used by the client", () => {
  assert.equal(framePackage(Buffer.from([1, 2, 3])).toString("hex"), "0003010203");
});
